### PR TITLE
Updates for Swift 4.2

### PR DESCRIPTION
**Pull request by jangbl**
Some things have been renamed or deprecated in `Swift 4.2`.

This PR takes care of that and makes sure that the project works with `Swift 4.2`.

I just applied `XCode's` suggestions, so no functionality was changed.

### CODE REVIEW

**Comment by antoninbiret** [comment]
Hi @productioncoder, thanks for the PR. The build seems to fail because Travis tries to build with Xcode 9, could you edit the `osx_image` property in `.travis.yml` and set `xcode10.1` ?

Thanks

**Comment by antoninbiret** [comment]
Merged. Thank you for your contribution @productioncoder. 
I'm going to push the new version on the spec repo.

**Comment by jangbl** [comment]
Thanks @antoninbiret 

That was lightening fast 🤓.
Happy New Year and thanks for this awesome pod! 👍

**Comment by antoninbiret** [comment]
The new version is live (`0.2.2`). 
Thanks again and Happy new year  🎉

**Pull request merged**
